server:
  port: 8080
spring:
  sql:
    init:
      mode: embedded
#  datasource:
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
#    username: sa
#    password:
  jpa:
    defer-datasource-initialization: true